# FriendlyChat

use_frameworks!
platform :ios, '13.2'

pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'

target 'FriendlyChatSwift' do
end
